AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PingerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      FunctionName: service-pinger
      CodeUri: .                 # directory containing the crate's Cargo.toml
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [arm64]
      MemorySize: 128
      Timeout: 15
      Events:
        EveryMinute:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)